const GUID_GENERATION_STATUS = "GUID_GENERATION_STATUS";
const GENERATE_GUID = "GENERATE_GUID";
const GUID_LENGTH_CHANGED = "GUID_LENGTH_CHANGED";

export { GENERATE_GUID, GUID_LENGTH_CHANGED, GUID_GENERATION_STATUS };
