const GUID_GENERATION_STATUS = "GUID_GENERATION_STATUS";
const GENERATE_GUID = "GENERATE_GUID";
const GUID_LENGTH_CHANGED = "GUID_LENGTH_CHANGED";
const COPY_GUID = "COPY_GUID";
const GUID_COPIED = "GUID_COPIED";

export {
  GENERATE_GUID,
  GUID_LENGTH_CHANGED,
  GUID_GENERATION_STATUS,
  COPY_GUID,
  GUID_COPIED
};
